import { useState, useEffect } from "react";
import { Input, Spacer, Grid } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// css stuff
const css = require("./styles.module.css");
export default function Login() {
  const [mail, setMail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <h1>Login</h1>
        <Grid.Container gap={3} justify="center">
          <Grid>
            <Input
              labelPlaceholder="Mail"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setMail(e.target.value);
              }}
            />
          </Grid>
          <Grid>
            <Input.Password
              labelPlaceholder="Password"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setPassword(e.target.value);
              }}
            />
          </Grid>
        </Grid.Container>
        <p>
          No account? <a href="/register">Register</a>
        </p>
      </main>
    </>
  );
}
