import { useState, useEffect } from "react";
import { Input, Spacer, Grid, Button } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// css stuff
const css = require("./styles.module.css");

// bypass nextui typing
type InputColor =
  | "default"
  | "primary"
  | "secondary"
  | "success"
  | "warning"
  | "error";

export default function Login() {
  const [mail, setMail] = useState("");
  const [password, setPassword] = useState("");

  //component handling
  const [mailInputColor, setMailInputColor] = useState<InputColor>("error");
  const [passwordInputColor, setPasswordInputColor] =
    useState<InputColor>("error");

  useEffect(() => {
    if (mail) {
      setMailInputColor("success");
    }
  }, [mail]);

  useEffect(() => {
    if (password) {
      setPasswordInputColor("success");
    }
  }, [password]);

  // Handleclick
  function handleClick(mail: string, password: string) {
    if (!username && !mail && !password) {
      console.log("register");
    } else {
      console.log("can't register");
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <h1>Login</h1>
        <Grid.Container gap={3} justify="center">
          <Grid>
            <Input
              color={mailInputColor}
              labelPlaceholder="Mail"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setMail(e.target.value);
              }}
            />
          </Grid>
          <Grid>
            <Input.Password
              color={passwordInputColor}
              labelPlaceholder="Password"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setPassword(e.target.value);
              }}
            />
          </Grid>
        </Grid.Container>
        <Spacer y={0.25} />
        <Button
          color="gradient"
          onClick={() => {
            handleClick(mail, password);
          }}
        >
          Register
        </Button>
        <Spacer y={0.5} />
        <p>
          No account? <a href="/register">Register</a>
        </p>
      </main>
    </>
  );
}
