import { useState, useEffect } from "react";
import { Input, Spacer, Grid, Button, Tooltip } from "@nextui-org/react";
import { useRouter } from "next/navigation";
import Head from "next/head";
import { getAuth } from "firebase/auth";

// css stuff
const css = require("./styles.module.css");

// utils
import validateEmail from "@/utils/check_email";
// import AuthAccess from "@/utils/auth_access";

// bypass nextui typing
type InputColor =
  | "default"
  | "primary"
  | "secondary"
  | "success"
  | "warning"
  | "error";

// api
import login from "../api/auth/firebase/auth_login";

// firebase shit
import firebaseApp from "@/firebaseconfig";
const auth = getAuth(firebaseApp);

// -------------- COMPONENT

export default function Login() {
  const router = useRouter();

  // states
  const [mail, setMail] = useState("");
  const [password, setPassword] = useState("");

  //component handling
  const [mailInputColor, setMailInputColor] = useState<InputColor>("error");
  const [passwordInputColor, setPasswordInputColor] =
    useState<InputColor>("error");
  const [isDisabled, setIsDisabled] = useState(true);

  // const [mailTooltipText, setMailTooltipText] = useState("Email not valid");
  // const [passwordTooltipText, setPasswordTooltipText] =
  //   useState("Password not valid");

  const [mailTooltipDisabled, setMailTooltipDisabled] = useState(false);
  const [passwordTooltipDisabled, setPasswordTooltipDisabled] = useState(false);

  // -------------- components stuff
  useEffect(() => {
    if (validateEmail(mail)) {
      setMailInputColor("success");
      setMailTooltipDisabled(true);
    } else {
      setMailInputColor("error");
      setMailTooltipDisabled(false);
    }
  }, [mail]);

  useEffect(() => {
    if (password.length > 5) {
      setPasswordInputColor("success");
      setPasswordTooltipDisabled(true);
    } else {
      setPasswordInputColor("error");
      setPasswordTooltipDisabled(false);
    }
  }, [password]);

  // button enabled
  useEffect(() => {
    if (validateEmail(mail) && password.length > 5) {
      setIsDisabled(false);
    } else {
      setIsDisabled(true);
    }
  }, [mail, password]);

  // Handleclick
  async function handleClick(mail: string, password: string) {
    if (validateEmail(mail) && password.length > 5) {
      const request = await login(mail, password);
      if (request) {
        router.push("/chat");
      }
    } else {
      console.log("can't register");
    }
  }

  // --------------------- FIRST LOAD
  useEffect(() => {
    (async () => {
      getAuth(firebaseApp).onAuthStateChanged(function (user) {
        if (user) {
          router.push("/chat");
        }
      });
    })();
  }, []);

  // --------------------- TSX

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <h1>Login</h1>
        <Grid.Container gap={3} justify="center">
          <Grid>
            <Tooltip
              content="Mail not valid!"
              trigger="hover"
              color={mailInputColor}
              isDisabled={mailTooltipDisabled}
            >
              <Input
                color={mailInputColor}
                labelPlaceholder="Mail"
                width="250px"
                clearable
                underlined
                onChange={(e) => {
                  setMail(e.target.value);
                }}
              />
            </Tooltip>
          </Grid>
          <Grid>
            <Tooltip
              content="Password not valid!"
              trigger="hover"
              color={passwordInputColor}
              isDisabled={passwordTooltipDisabled}
            >
              <Input.Password
                color={passwordInputColor}
                labelPlaceholder="Password"
                width="250px"
                clearable
                underlined
                onChange={(e) => {
                  setPassword(e.target.value);
                }}
              />
            </Tooltip>
          </Grid>
        </Grid.Container>
        <Spacer y={0.25} />
        <Button
          color="gradient"
          onPress={() => {
            handleClick(mail, password);
          }}
          disabled={isDisabled}
        >
          Login
        </Button>
        <Spacer y={0.5} />
        <p>
          No account? <a href="/register">Register</a>
        </p>
      </main>
    </>
  );
}
