import { useState, useEffect } from "react";
import {
  Input,
  Spacer,
  Grid,
  Button,
  Tooltip,
  normalColors,
  NormalColors,
} from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// css stuff
const css = require("./styles.module.css");
const inter = Inter({ subsets: ["latin"] });

// utils
import validateEmail from "../../utils";

type InputColor =
  | "default"
  | "primary"
  | "secondary"
  | "success"
  | "warning"
  | "error";

// requests to firebase
import register from "@/index";

export default function Register() {
  // data
  const [username, setUsername] = useState("");
  const [mail, setMail] = useState("");
  const [password, setPassword] = useState("");

  // component handling
  const [isDisabled, setIsDisabled] = useState(true);

  // colors
  const [usernameInputColor, setUsernameInputColor] =
    useState<InputColor>("error");
  const [mailInputColor, setMailInputColor] = useState<InputColor>("error");
  const [passwordInputColor, setPasswordInputColor] =
    useState<InputColor>("error");

  // components useEffect
  useEffect(() => {
    if (username) {
      setUsernameInputColor("success");
    } else {
      setUsernameInputColor("error");
    }
  }, [username]);

  useEffect(() => {
    if (validateEmail(mail)) {
      setMailInputColor("success");
    } else {
      setUsernameInputColor("error");
    }
  }, [mail]);

  useEffect(() => {
    if (password) {
      setPasswordInputColor("success");
    } else {
      setUsernameInputColor("error");
    }
  }, [password]);

  // Handleclick
  function handleClick(mail: string, password: string) {
    if (!username && !mail && !password) {
      register(mail, password);
    }
  }

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <h1 className={inter.className}>Register</h1>
        <Grid.Container gap={3} justify="center" className={inter.className}>
          <Grid>
            <Input
              color={usernameInputColor}
              labelPlaceholder="Username"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setUsername(e.target.value);
              }}
            />
          </Grid>
          <Grid>
            <Input
              color={mailInputColor}
              labelPlaceholder="Mail"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setMail(e.target.value);
              }}
            />
          </Grid>
          <Grid>
            <Input.Password
              color={passwordInputColor}
              labelPlaceholder="Password"
              width="250px"
              clearable
              underlined
              onChange={(e) => {
                setPassword(e.target.value);
              }}
            />
          </Grid>
        </Grid.Container>
        <Spacer y={0.25} />
        <Button
          color="gradient"
          onClick={() => {
            handleClick(mail, password);
          }}
        >
          Register
        </Button>
        <Spacer y={0.5} />
        <p className={inter.className}>
          Already have an account? <a href="/login">Login</a>
        </p>
      </main>
    </>
  );
}
