import { useEffect, useState } from "react";
import { Input, Spacer } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { getAuth } from "firebase/auth";

// css stuff
const css = require("./styles.module.css");
const inter = Inter({ subsets: ["latin"] });

// components
import Message from "@/components/Chat/Message/Message";
import SettingsButton from "@/components/Buttons/SettingsButton/SettingsButton";
import { SendButton } from "@/components/Buttons/SendButton/SendButton";
import { Send } from "react-iconly";

// firebase shit
import firebaseApp from "@/firebaseconfig";
import getCurrentUser from "../api/auth/firebase/get_current_user";
import LogoutButton from "@/components/Buttons/LogoutButton/LogoutButton";
const auth = getAuth(firebaseApp);

// api

export default function Chat() {
  const router = useRouter();

  const [input, setInput] = useState("");

  // worst code i willl evver write smh

  useEffect(() => {
    (async () => {
      getAuth(firebaseApp).onAuthStateChanged(function (user) {
        if (user) {
          const loggedUser = getCurrentUser(user);
          console.log(loggedUser);
        } else {
          router.push("/login");
        }
      });
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <SettingsButton />
        <LogoutButton />
        <div className={css.chatContainer}>
          <Message
            username="Test"
            content="retardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretardretard"
            date={1684492038065}
            imgUrl={null}
          />
          <div className={css.userInputContainer}>
            <Input
              clearable
              contentRightStyling={false}
              placeholder="Type your message..."
              contentRight={
                <SendButton>
                  <Send />
                </SendButton>
              }
              size="xl"
              fullWidth
            />
          </div>
        </div>
      </main>
    </>
  );
}
