import { Input, Spacer } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// css stuff
const css = require("./styles.module.css");
const inter = Inter({ subsets: ["latin"] });

// components
import Message from "@/components/Message/Message";
import SettingsButton from "@/components/SettingsButton/SettingsButton";

export default function Chat() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <SettingsButton />
      </main>
    </>
  );
}
