import { Input, Spacer, Button, Grid } from "@nextui-org/react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Camera } from "react-iconly";

// css stuff
const css = require("./styles.module.css");
const inter = Inter({ subsets: ["latin"] });

export default function Settings() {
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css.body}>
        <h1 className={inter.className}>Settings</h1>
        <div>
          <Spacer y={0.5} />
          <Grid.Container gap={2}>
            <Grid>
              <Button className={inter.className}>Change Username</Button>
            </Grid>
            <Grid>
              <Button
                auto
                icon={<Camera set="curved" primaryColor="white" />}
              />
            </Grid>
          </Grid.Container>
          <Spacer y={0.5} />
        </div>
        <p className={inter.className}>
          Found a bug?{" "}
          <a href="https://github.com/Rurucchi/nextchat/issues" target="_blank">
            Open an issue
          </a>
        </p>
      </main>
    </>
  );
}
